export const API_URLS = {
    USER_LOGIN_ENDPOINT: 'http://localhost:8069/api/v1/tracker-manager-service/user/login',
    LOGIN_REQUEST_OTP_ENDPOINT: 'http://localhost:8069/api/v1/tracker-manager-service/user/otp-login',
    USER_REGISTRATION_ENDPOINT: 'http://localhost:8069/api/v1/tracker-manager-service/user/register',
    FORGOT_PASSWORD_REQUEST_OTP_ENDPOINT: 'http://localhost:8069/api/v1/tracker-manager-service/forgot-password/request-otp',
    FORGOT_PASSWORD_RESET_ENDPOINT: 'http://localhost:8069/api/v1/tracker-manager-service/forgot-password/reset',
    VERIFY_OTP_ENDPOINT: 'http://localhost:8069/api/v1/tracker-manager-service/auth/verify-otp',
    VEHICLE_REGISTRATION_ENDPOINT : 'http://localhost:8069/api/v1/tracker-manager-service/vehicle/register',
    FETCH_ALL_VEHICLE_ENDPOINT : 'http://localhost:8069/api/v1/tracker-manager-service/vehicle/fetch',
    FETCH_VEHICLES_BY_USER_ENDPOINT : 'http://localhost:8069/api/v1/tracker-manager-service/user-vehicle/fetch',
    DELETE_VEHICLE_ENDPOINT : 'http://localhost:8069/api/v1/tracker-manager-service/vehicle',
    UPDATE_VEHICLE_ENDPOINT : 'http://localhost:8069/api/v1/tracker-manager-service/vehicle',
    FETCH_ALL_USERS_ENDPOINT : 'http://localhost:8069/api/v1/tracker-manager-service/user/fetch',
    USER_ENDPOINT : 'http://localhost:8069/api/v1/tracker-manager-service/user',
    VEHICLE_FUEL_EXPENSE_ENDPOINT : 'http://localhost:8069/api/v1/tracker-manager-service/vehicle/fuel-expense',
    STOCK_MARKET_NIFTY_DATA_ENDPOINT : 'http://localhost:8069/api/v1/tracker-manager-service/stock/nifty-data',
    VEHICLE_SERVICING_ENDPOINT : 'http://localhost:8069/api/v1/tracker-manager-service/vehicle/service',
    CREDENTIALS_ENDPOINT : 'http://localhost:8069/api/v1/tracker-manager-service/credentials',
    BANK_ACCOUNT_ENDPOINT: 'http://localhost:8069/api/v1/tracker-manager-service/financial/bank-account',
    FETCH_BANK_ACCOUNT_BY_USER_ENDPOINT : 'http://localhost:8069/api/v1/tracker-manager-service/financial/user-bank-account'
  };